FROM stratospire/aws-lambda-elixir-runtime-builder:1.9.1

COPY . .

ARG MIX_ENV=prod
ENV MIX_ENV=${MIX_ENV}

RUN mix do deps.get, compile, release, lambda.bootstrap, lambda.zip

CMD echo "output: /workspace/lambda.zip"
